# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop', models.IntegerField()),
                ('to_stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixbus.Route')),
            ],
            options={
                'ordering': ('route', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop', models.IntegerField()),
                ('to_stop', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stop', models.IntegerField()),
                ('to_stop', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('transaction_has', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixbus.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='routesegment',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixbus.Segment'),
        ),
        migrations.AddField(
            model_name='route',
            name='segments',
            field=models.ManyToManyField(through='flixbus.RouteSegment', to='flixbus.Segment'),
        ),
        migrations.AddField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flixbus.Route'),
        ),
    ]
